### ISSUE TITLE
Signed Document not Downloading

### ISSUE THREAD

**Issue by Ajita24** [docusign/docusign-soap-sdk#49]
I have downloaded DocuSign-eSignature MS.Net sample from https://github.com/docusign/DocuSign-eSignature-SDK

The code runs correctly and gets the documents signed from the recipients.However when we try to download the signed document by clicking Download button available under GetStatusAndDocs section then code mentioned below throws error,

This demo has encountered an error: Timeouts are not supported on this stream.
Please correct the issue and try again.

 DocuSignAPI.EnvelopePDF pdf = client.RequestPDF(id) ;

This error is encountered only when the document is a pdf file.Works fine in case of text files.

**Comment by LarryKlugerDS** [comment]
This software is deprecated. Developers who wish to develop with SOAP should generate their own stubs using the wdsl. Thank you.
