### ISSUE TITLE
How to use with oAuth token

### ISSUE THREAD

**Issue by d668** [docusign/docusign-soap-sdk#52]
I understand that the this API will be deprecated, so how can I use SDK with new API and particularly with oAuth tokens?

**Comment by sonalmahajan01** [comment]
Hi @intergleam,  were u able to find this out? I need to do the same.

**Comment by LarryKlugerDS** [comment]
At this time, the DocuSign SOAP eSignature API is not planned to be deprecated. 
However, new eSignature features are usually not added to the SOAP API.
Therefore we strongly recommend that all new applications should use the eSignature REST API.

## Re: OAuth authentication for the SOAP API
Currently, this is not supported. It may be supported in the future, but we don't yet have a committed project in Engineering to do so.
